"""added proxy 

Revision ID: 09014b1fb524
Revises: 1d1a27b4d068
Create Date: 2024-09-15 23:37:39.528134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09014b1fb524'
down_revision = '1d1a27b4d068'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
