"""changed

Revision ID: 0dbb07de1d7c
Revises: a6f67a35de98
Create Date: 2024-08-12 23:25:49.156772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dbb07de1d7c'
down_revision = 'a6f67a35de98'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegramId', sa.Integer(), nullable=True),
    sa.Column('accountId', sa.BigInteger(), nullable=True),
    sa.Column('isPaid', sa.Boolean(), nullable=True),
    sa.Column('isGrantGiven', sa.Boolean(), nullable=True),
    sa.Column('currentPeriodStart', sa.DateTime(), nullable=True),
    sa.Column('currentPeriodEnd', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blum_account_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('accountId', sa.Integer(), nullable=True),
    sa.Column('availablePlayPasses', sa.Integer(), nullable=True),
    sa.Column('allPlayPasses', sa.Integer(), nullable=True),
    sa.Column('availableBalance', sa.String(), nullable=True),
    sa.Column('farmingFreezeHours', sa.Integer(), nullable=True),
    sa.Column('needRemind', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['accountId'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('account', 'farmingFreezeHours')
    op.drop_column('account', 'availableBalance')
    op.drop_column('account', 'needRemind')
    op.drop_column('account', 'allPlayPasses')
    op.drop_column('account', 'availablePlayPasses')
    op.drop_column('user', 'isGrantGiven')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('isGrantGiven', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('account', sa.Column('availablePlayPasses', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('account', sa.Column('allPlayPasses', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('account', sa.Column('needRemind', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('account', sa.Column('availableBalance', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('account', sa.Column('farmingFreezeHours', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_table('blum_account_details')
    op.drop_table('account_subscription')
    # ### end Alembic commands ###
