"""added tg stars

Revision ID: 11e68ace73b1
Revises: 48ddd885f659
Create Date: 2024-08-24 14:27:59.336850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11e68ace73b1'
down_revision = '48ddd885f659'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_payment', sa.Column('stars', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_payment', 'stars')
    # ### end Alembic commands ###
