"""added proxy 

Revision ID: 1d1a27b4d068
Revises: d359230134d6
Create Date: 2024-09-15 15:35:41.688789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d1a27b4d068'
down_revision = 'd359230134d6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proxy', sa.Column('isCommon', sa.Boolean(), nullable=True))
    op.add_column('proxy', sa.Column('phoneCode', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proxy', 'phoneCode')
    op.drop_column('proxy', 'isCommon')
    # ### end Alembic commands ###
