"""changed

Revision ID: 30a800c7817d
Revises: 0dbb07de1d7c
Create Date: 2024-08-12 23:46:43.658526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30a800c7817d'
down_revision = '0dbb07de1d7c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('blum_account_details_accountId_fkey', 'blum_account_details', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('blum_account_details_accountId_fkey', 'blum_account_details', 'account', ['accountId'], ['id'])
    # ### end Alembic commands ###
