"""Added needRemind

Revision ID: 384dda6a9c98
Revises: a769928531e2
Create Date: 2024-07-05 15:31:39.096726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '384dda6a9c98'
down_revision = 'a769928531e2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('needRemind', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'needRemind')
    # ### end Alembic commands ###
