"""changed

Revision ID: 3cfa858f17c3
Revises: a83a80d16b32
Create Date: 2024-07-21 23:26:35.931249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cfa858f17c3'
down_revision = 'a83a80d16b32'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
