"""account isOver

Revision ID: 45b19fa4a0d9
Revises: 89c0150eff6a
Create Date: 2024-09-29 15:35:21.677516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45b19fa4a0d9'
down_revision = '89c0150eff6a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('isOver', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'isOver')
    # ### end Alembic commands ###
