"""checker blum games 

Revision ID: 48ddd885f659
Revises: 7039ef9f5d96
Create Date: 2024-08-23 19:49:28.301084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48ddd885f659'
down_revision = '7039ef9f5d96'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blum_account', sa.Column('playedGames', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blum_account', 'playedGames')
    # ### end Alembic commands ###
