"""added orderinvoice

Revision ID: 520bc17c0c9e
Revises: e7ed4a9c5841
Create Date: 2024-06-29 18:45:45.364838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '520bc17c0c9e'
down_revision = 'e7ed4a9c5841'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_invoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegramId', sa.BigInteger(), nullable=True),
    sa.Column('userPaymentId', sa.Integer(), nullable=True),
    sa.Column('invoiceId', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('payedAmount', sa.Float(), nullable=True),
    sa.Column('cryptoCurrency', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('expirationTime', sa.DateTime(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegramId'),
    sa.UniqueConstraint('userPaymentId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_invoice')
    # ### end Alembic commands ###
