"""added proxy model

Revision ID: 5e28b1914b88
Revises: a3ea435b5ecb
Create Date: 2024-08-22 20:25:01.449347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e28b1914b88'
down_revision = 'a3ea435b5ecb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proxy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegramId', sa.BigInteger(), nullable=True),
    sa.Column('proxyId', sa.String(), nullable=True),
    sa.Column('ip', sa.String(), nullable=True),
    sa.Column('host', sa.String(), nullable=True),
    sa.Column('port', sa.String(), nullable=True),
    sa.Column('user', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('dateEnd', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegramId')
    )
    op.add_column('account', sa.Column('proxyId', sa.BigInteger(), nullable=True))
    op.drop_column('account', 'proxy')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('proxy', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('account', 'proxyId')
    op.drop_table('proxy')
    # ### end Alembic commands ###
