"""account isOver

Revision ID: 64b86002246b
Revises: 45b19fa4a0d9
Create Date: 2024-09-29 16:29:37.802536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64b86002246b'
down_revision = '45b19fa4a0d9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
