"""auto increment

Revision ID: 7039ef9f5d96
Revises: f91aadc3b714
Create Date: 2024-08-23 18:42:31.953742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7039ef9f5d96'
down_revision = 'f91aadc3b714'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
