"""Migrated

Revision ID: 89c0150eff6a
Revises: acd8abd6518a
Create Date: 2024-09-28 11:38:27.058266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89c0150eff6a'
down_revision = 'acd8abd6518a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
