"""changed

Revision ID: a6f67a35de98
Revises: 3cfa858f17c3
Create Date: 2024-08-04 22:21:28.662336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6f67a35de98'
down_revision = '3cfa858f17c3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('proxy', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'proxy')
    # ### end Alembic commands ###
