"""Changed

Revision ID: a769928531e2
Revises: d958371609ab
Create Date: 2024-07-03 15:34:42.474537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a769928531e2'
down_revision = 'd958371609ab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('paidCryptoAmount', sa.Float(), nullable=True))
    op.add_column('order', sa.Column('paidAmount', sa.Float(), nullable=True))
    op.add_column('order', sa.Column('exchangeRate', sa.Float(), nullable=True))
    op.drop_column('order', 'payedAmount')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('payedAmount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('order', 'exchangeRate')
    op.drop_column('order', 'paidAmount')
    op.drop_column('order', 'paidCryptoAmount')
    # ### end Alembic commands ###
