"""Added isCanceled in proxy

Revision ID: acd8abd6518a
Revises: 610fde0ae7b9
Create Date: 2024-09-28 01:03:14.606340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acd8abd6518a'
down_revision = '610fde0ae7b9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proxy', sa.Column('isCanceled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proxy', 'isCanceled')
    # ### end Alembic commands ###
