"""changed

Revision ID: b081934bb98e
Revises: 520bc17c0c9e
Create Date: 2024-06-29 18:53:49.819976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b081934bb98e'
down_revision = '520bc17c0c9e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('order_invoice_telegramId_key', 'order_invoice', type_='unique')
    op.drop_constraint('order_invoice_userPaymentId_key', 'order_invoice', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('order_invoice_userPaymentId_key', 'order_invoice', ['userPaymentId'])
    op.create_unique_constraint('order_invoice_telegramId_key', 'order_invoice', ['telegramId'])
    # ### end Alembic commands ###
