"""changed

Revision ID: b34bf8819918
Revises: 34da36cb3cd9
Create Date: 2024-08-18 17:33:10.099956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b34bf8819918'
down_revision = '34da36cb3cd9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'isGrantGiven')
    op.add_column('user', sa.Column('isGrantGiven', sa.Boolean(), nullable=True))
    op.add_column('user_payment', sa.Column('trialBalance', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_payment', 'trialBalance')
    op.add_column('user', sa.Column('isFreeTrial', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('user', 'isGrantGiven')
    # ### end Alembic commands ###
