"""removed unique tg id

Revision ID: c3a085e993c8
Revises: 924137209a79
Create Date: 2024-08-22 23:57:59.369070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3a085e993c8'
down_revision = '924137209a79'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('proxy_telegramId_key', 'proxy', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('proxy_telegramId_key', 'proxy', ['telegramId'])
    # ### end Alembic commands ###
