"""Added inuse in proxy

Revision ID: d359230134d6
Revises: 11e68ace73b1
Create Date: 2024-08-29 12:51:35.692168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd359230134d6'
down_revision = '11e68ace73b1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proxy', sa.Column('inUse', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proxy', 'inUse')
    # ### end Alembic commands ###
