"""changed

Revision ID: d803c7eb0fab
Revises: 30a800c7817d
Create Date: 2024-08-17 11:56:35.715566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd803c7eb0fab'
down_revision = '30a800c7817d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blum_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('accountId', sa.Integer(), nullable=True),
    sa.Column('availablePlayPasses', sa.Integer(), nullable=True),
    sa.Column('allPlayPasses', sa.Integer(), nullable=True),
    sa.Column('availableBalance', sa.String(), nullable=True),
    sa.Column('farmingFreezeHours', sa.Integer(), nullable=True),
    sa.Column('needRemind', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('blum_account_details')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blum_account_details',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('accountId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('availablePlayPasses', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('allPlayPasses', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('availableBalance', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('farmingFreezeHours', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('needRemind', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='blum_account_details_pkey')
    )
    op.drop_table('blum_account')
    # ### end Alembic commands ###
