"""changed

Revision ID: d958371609ab
Revises: a3ee587f5108
Create Date: 2024-06-30 17:20:36.903188

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd958371609ab'
down_revision = 'a3ee587f5108'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegramId', sa.BigInteger(), nullable=True),
    sa.Column('userPaymentId', sa.Integer(), nullable=True),
    sa.Column('invoiceId', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('payedAmount', sa.Float(), nullable=True),
    sa.Column('cryptoCurrency', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('errorStatus', sa.String(), nullable=True),
    sa.Column('network', sa.String(), nullable=True),
    sa.Column('expirationTime', sa.DateTime(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('order_invoice')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_invoice',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('telegramId', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('userPaymentId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('invoiceId', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('payedAmount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('cryptoCurrency', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('expirationTime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('errorStatus', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('network', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='order_invoice_pkey')
    )
    op.drop_table('order')
    # ### end Alembic commands ###
