"""init

Revision ID: e7ed4a9c5841
Revises: 
Create Date: 2024-06-23 15:31:18.584766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7ed4a9c5841'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegramId', sa.BigInteger(), nullable=True),
    sa.Column('phoneNumber', sa.String(), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('sessionName', sa.String(), nullable=True),
    sa.Column('availablePlayPasses', sa.Integer(), nullable=True),
    sa.Column('allPlayPasses', sa.Integer(), nullable=True),
    sa.Column('availableBalance', sa.String(), nullable=True),
    sa.Column('farmingFreezeHours', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('lastUpdated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phoneNumber'),
    sa.UniqueConstraint('telegramId')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegramId', sa.BigInteger(), nullable=True),
    sa.Column('firstName', sa.String(), nullable=True),
    sa.Column('lastName', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('languageCode', sa.String(), nullable=True),
    sa.Column('referredBy', sa.String(), nullable=True),
    sa.Column('referralUsers', sa.JSON(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('lastUpdated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegramId')
    )
    op.create_table('user_payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegramId', sa.BigInteger(), nullable=True),
    sa.Column('userId', sa.BigInteger(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegramId'),
    sa.UniqueConstraint('userId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_payment')
    op.drop_table('user')
    op.drop_table('account')
    # ### end Alembic commands ###
